import React from 'react';
import { Alert, SpaceBetween } from '@cloudscape-design/components';

export const ManageNotificationsHelp = () => (
  <div>
    <SpaceBetween direction="vertical" size="s">
      <Alert
        type="info"
        header="Manage Notifications Dashboard"
      >
        The Manage Notifications dashboard will provide administrators with a centralized interface to configure, monitor, and manage all notifications generated by the Appointment Booking Solution (ABS). This includes confirmation messages, reminders, rescheduling alerts, and service updates across multiple communication channels such as email, SMS, and telephone. Administrators will be able to set notification rules, modify templates, track delivery statuses, and ensure compliance with client communication preferences. The dashboard will also offer audit logs and real-time analytics, allowing authorized users to review notification history, troubleshoot failed deliveries, and optimize communication workflows. Additionally, the system will support multilingual notifications and allow customization of message content per service module, ensuring that applicants receive timely and relevant updates in their preferred language and format.
      </Alert>
    </SpaceBetween>
    <h2>Manage Notifications Help</h2>
    <p>The Manage Notifications dashboard allows administrators to manage notifications generated by the Appointment Booking Solution (ABS). This includes configuring notification rules, modifying templates, tracking delivery statuses, and ensuring compliance with client communication preferences. The dashboard also provides audit logs and real-time analytics for reviewing notification history and optimizing communication workflows.</p>
  </div>
);
