CREATE TABLE IF NOT EXISTS iset_client_merge_audit (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  surviving_client_id BIGINT UNSIGNED NOT NULL,
  merged_client_id BIGINT UNSIGNED NOT NULL,
  merged_by_staff_profile_id BIGINT UNSIGNED DEFAULT NULL,
  merge_reason VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  notes TEXT COLLATE utf8mb4_unicode_ci,
  metadata_json JSON DEFAULT NULL,
  merged_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_client_merge_audit_surviving (surviving_client_id, merged_at),
  KEY idx_client_merge_audit_merged (merged_client_id, merged_at),
  KEY idx_client_merge_audit_actor (merged_by_staff_profile_id),
  CONSTRAINT fk_client_merge_audit_surviving FOREIGN KEY (surviving_client_id) REFERENCES client (id) ON DELETE RESTRICT,
  CONSTRAINT fk_client_merge_audit_merged FOREIGN KEY (merged_client_id) REFERENCES client (id) ON DELETE RESTRICT,
  CONSTRAINT fk_client_merge_audit_actor FOREIGN KEY (merged_by_staff_profile_id) REFERENCES staff_profiles (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS iset_case_merge_audit (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  surviving_case_id BIGINT UNSIGNED NOT NULL,
  merged_case_id BIGINT UNSIGNED NOT NULL,
  surviving_client_id BIGINT UNSIGNED DEFAULT NULL,
  merged_client_id BIGINT UNSIGNED DEFAULT NULL,
  merged_by_staff_profile_id BIGINT UNSIGNED DEFAULT NULL,
  merge_reason VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  repointed_application_count INT UNSIGNED NOT NULL DEFAULT 0,
  notes TEXT COLLATE utf8mb4_unicode_ci,
  metadata_json JSON DEFAULT NULL,
  merged_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_case_merge_audit_surviving (surviving_case_id, merged_at),
  KEY idx_case_merge_audit_merged (merged_case_id, merged_at),
  KEY idx_case_merge_audit_surviving_client (surviving_client_id),
  KEY idx_case_merge_audit_merged_client (merged_client_id),
  KEY idx_case_merge_audit_actor (merged_by_staff_profile_id),
  CONSTRAINT fk_case_merge_audit_surviving FOREIGN KEY (surviving_case_id) REFERENCES iset_case (id) ON DELETE RESTRICT,
  CONSTRAINT fk_case_merge_audit_merged FOREIGN KEY (merged_case_id) REFERENCES iset_case (id) ON DELETE RESTRICT,
  CONSTRAINT fk_case_merge_audit_surviving_client FOREIGN KEY (surviving_client_id) REFERENCES client (id) ON DELETE SET NULL,
  CONSTRAINT fk_case_merge_audit_merged_client FOREIGN KEY (merged_client_id) REFERENCES client (id) ON DELETE SET NULL,
  CONSTRAINT fk_case_merge_audit_actor FOREIGN KEY (merged_by_staff_profile_id) REFERENCES staff_profiles (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
