ALTER TABLE iset_case_intervention
  ADD COLUMN delivery_status VARCHAR(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL AFTER status,
  ADD KEY idx_case_intervention_delivery_status (delivery_status);

CREATE TABLE IF NOT EXISTS iset_intervention_proposal (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  case_id BIGINT UNSIGNED NOT NULL,
  action_plan_id BIGINT UNSIGNED DEFAULT NULL,
  application_id BIGINT UNSIGNED DEFAULT NULL,
  legacy_intervention_id BIGINT UNSIGNED DEFAULT NULL,
  source_intervention_id BIGINT UNSIGNED DEFAULT NULL,
  proposal_kind VARCHAR(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'new',
  review_status VARCHAR(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
  title VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  intervention_code TINYINT UNSIGNED DEFAULT NULL,
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  proposed_cost DECIMAL(14,2) DEFAULT NULL,
  decision_reason VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  decision_notes TEXT COLLATE utf8mb4_unicode_ci,
  payload_json JSON DEFAULT NULL,
  metadata_json JSON DEFAULT NULL,
  submitted_by_staff_profile_id BIGINT UNSIGNED DEFAULT NULL,
  reviewed_by_staff_profile_id BIGINT UNSIGNED DEFAULT NULL,
  submitted_at DATETIME DEFAULT NULL,
  reviewed_at DATETIME DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  archived_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_intervention_proposal_legacy_intervention (legacy_intervention_id),
  KEY idx_intervention_proposal_case_review (case_id, review_status),
  KEY idx_intervention_proposal_action_plan (action_plan_id),
  KEY idx_intervention_proposal_application (application_id),
  KEY idx_intervention_proposal_source_intervention (source_intervention_id),
  KEY idx_intervention_proposal_review_status (review_status),
  KEY idx_intervention_proposal_submitted_by (submitted_by_staff_profile_id),
  KEY idx_intervention_proposal_reviewed_by (reviewed_by_staff_profile_id),
  CONSTRAINT fk_intervention_proposal_case FOREIGN KEY (case_id) REFERENCES iset_case (id) ON DELETE CASCADE,
  CONSTRAINT fk_intervention_proposal_action_plan FOREIGN KEY (action_plan_id) REFERENCES iset_case_action_plan (id) ON DELETE SET NULL,
  CONSTRAINT fk_intervention_proposal_application FOREIGN KEY (application_id) REFERENCES iset_application (id) ON DELETE SET NULL,
  CONSTRAINT fk_intervention_proposal_legacy_intervention FOREIGN KEY (legacy_intervention_id) REFERENCES iset_case_intervention (id) ON DELETE SET NULL,
  CONSTRAINT fk_intervention_proposal_source_intervention FOREIGN KEY (source_intervention_id) REFERENCES iset_case_intervention (id) ON DELETE SET NULL,
  CONSTRAINT fk_intervention_proposal_submitted_by FOREIGN KEY (submitted_by_staff_profile_id) REFERENCES staff_profiles (id) ON DELETE SET NULL,
  CONSTRAINT fk_intervention_proposal_reviewed_by FOREIGN KEY (reviewed_by_staff_profile_id) REFERENCES staff_profiles (id) ON DELETE SET NULL,
  CONSTRAINT chk_intervention_proposal_kind CHECK (proposal_kind IN ('new', 'revision')),
  CONSTRAINT chk_intervention_proposal_review_status CHECK (review_status IN ('draft', 'submitted', 'in_review', 'changes_requested', 'approved', 'rejected', 'withdrawn'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
