CREATE TABLE IF NOT EXISTS iset_applicant_watchlist (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  full_name VARCHAR(255) NOT NULL,
  first_name VARCHAR(100) DEFAULT NULL,
  last_name VARCHAR(100) DEFAULT NULL,
  dob DATE NOT NULL,
  sin VARCHAR(16) NOT NULL,
  sin_hash CHAR(64) NOT NULL,
  notes TEXT DEFAULT NULL,
  source_case_id BIGINT UNSIGNED DEFAULT NULL,
  source_application_id BIGINT UNSIGNED DEFAULT NULL,
  created_by_staff_profile_id BIGINT UNSIGNED DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uniq_applicant_watchlist_sin_hash (sin_hash),
  KEY idx_applicant_watchlist_name_dob (last_name, dob),
  KEY idx_applicant_watchlist_case (source_case_id, created_at),
  KEY idx_applicant_watchlist_application (source_application_id, created_at),
  KEY idx_applicant_watchlist_staff (created_by_staff_profile_id, created_at),
  CONSTRAINT fk_applicant_watchlist_case FOREIGN KEY (source_case_id) REFERENCES iset_case (id) ON DELETE SET NULL,
  CONSTRAINT fk_applicant_watchlist_application FOREIGN KEY (source_application_id) REFERENCES iset_application (id) ON DELETE SET NULL,
  CONSTRAINT fk_applicant_watchlist_staff FOREIGN KEY (created_by_staff_profile_id) REFERENCES staff_profiles (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
