CREATE TABLE IF NOT EXISTS iset_application_assessment (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  application_id BIGINT UNSIGNED NOT NULL,
  case_id BIGINT UNSIGNED NOT NULL,
  date_of_assessment DATE DEFAULT NULL,
  overview TEXT COLLATE utf8mb4_unicode_ci,
  employment_goals TEXT COLLATE utf8mb4_unicode_ci,
  previous_iset TINYINT(1) DEFAULT NULL,
  previous_iset_details TEXT COLLATE utf8mb4_unicode_ci,
  employment_barriers JSON DEFAULT NULL,
  local_area_priorities JSON DEFAULT NULL,
  other_funding_details TEXT COLLATE utf8mb4_unicode_ci,
  esdc_eligibility VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  intervention_start_date DATE DEFAULT NULL,
  intervention_end_date DATE DEFAULT NULL,
  intervention_budget_pot_id BIGINT UNSIGNED DEFAULT NULL,
  posting_context VARCHAR(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  intervention_code TINYINT UNSIGNED DEFAULT NULL,
  intervention_outcome_code TINYINT UNSIGNED DEFAULT NULL,
  intervention_duration_days SMALLINT UNSIGNED DEFAULT NULL,
  intervention_cost_total INT UNSIGNED DEFAULT NULL,
  intervention_related_noc VARCHAR(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  intervention_related_noc_version VARCHAR(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  childcare_need TINYINT(1) DEFAULT NULL,
  childcare_funding_details TEXT COLLATE utf8mb4_unicode_ci,
  action_plan_result_code VARCHAR(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  action_plan_result_date DATE DEFAULT NULL,
  institution VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  program_name VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  itp_payload JSON DEFAULT NULL,
  wage_payload JSON DEFAULT NULL,
  recommendation VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  justification TEXT COLLATE utf8mb4_unicode_ci,
  nwac_review VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  nwac_reason TEXT COLLATE utf8mb4_unicode_ci,
  employment_barriers_other_details TEXT COLLATE utf8mb4_unicode_ci,
  proposed_interventions JSON DEFAULT NULL,
  legacy_case_assessment_case_id BIGINT UNSIGNED DEFAULT NULL,
  legacy_backfill_reason VARCHAR(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  legacy_backfilled_at DATETIME DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_iset_application_assessment_application (application_id),
  KEY idx_iset_application_assessment_case (case_id),
  KEY idx_iset_application_assessment_pot (intervention_budget_pot_id),
  KEY idx_iset_application_assessment_legacy_case (legacy_case_assessment_case_id),
  CONSTRAINT fk_iset_application_assessment_application FOREIGN KEY (application_id) REFERENCES iset_application (id) ON DELETE CASCADE,
  CONSTRAINT fk_iset_application_assessment_case FOREIGN KEY (case_id) REFERENCES iset_case (id) ON DELETE CASCADE,
  CONSTRAINT fk_iset_application_assessment_pot FOREIGN KEY (intervention_budget_pot_id) REFERENCES budget_pot (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
