-- Guarded second recovery for feedback 178.
-- The first recovery was bypassed when the unchanged assessment was submitted
-- for another final decision instead of being returned to the Coordinator.
-- This transaction returns the assessment directly to the submitter and
-- withdraws only the artifacts generated by the unintended second approval.
-- Recovery snapshot: path-prod-feedback-178-second-recovery-20260806-2033

DROP PROCEDURE IF EXISTS prod_feedback_178_second_recovery_20260806;

DELIMITER //

CREATE PROCEDURE prod_feedback_178_second_recovery_20260806()
BEGIN
  DECLARE v_guard_count INT DEFAULT 0;

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    RESIGNAL;
  END;

  START TRANSACTION;

  IF BINARY DATABASE() <> BINARY 'iset_intake' THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_wrong_database';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM application_lock
   WHERE application_id = 61
     AND owner_user_id = 'prod-feedback-178-second-recovery-20260806'
     AND expires_at > CURRENT_TIMESTAMP
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_lock_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_application
   WHERE id = 61
     AND submission_id = 61
     AND client_id = 160
     AND case_id = 138
     AND status = 'approved'
     AND lifecycle_status = 'decision_recorded'
     AND decision_outcome = 'approved'
     AND awaiting_reason = 'none'
     AND closure_reason IS NULL
     AND row_version = 43
     AND updated_at = '2026-08-05 18:27:25'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_application_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case
   WHERE id = 138
     AND client_id = 160
     AND assigned_staff_profile_id = 5697
     AND status = 'dormant'
     AND lifecycle_status = 'dormant'
     AND portfolio_region_id = 1
     AND open_intervention_count = 0
     AND total_intervention_count = 0
     AND JSON_UNQUOTE(JSON_EXTRACT(
           case_context_json,
           '$.applicationDecisionLetters."61".assessment_nwac_review_status'
         )) = 'approve'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_case_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_application_assessment
   WHERE id = 207
     AND application_id = 61
     AND case_id = 138
     AND recommendation = 'recommend'
     AND nwac_review = 'agree'
     AND nwac_reason IS NULL
     AND updated_at = '2026-08-04 18:12:27'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_assessment_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_review_workflow
   WHERE id = 17
     AND workflow_type = 'application_assessment'
     AND subject_key = 'application_assessment:application:61'
     AND case_id = 138
     AND application_id = 61
     AND current_stage = 'final_decision_recorded'
     AND current_owner_role IS NULL
     AND current_owner_staff_profile_id IS NULL
     AND submitted_by_staff_profile_id = 5697
     AND rm_reviewed_by_staff_profile_id = 995581
     AND rm_reviewed_at = '2026-08-05 16:49:44'
     AND nwac_decided_by_staff_profile_id = 51
     AND nwac_decided_at = '2026-08-05 18:27:25'
     AND nwac_decision = 'approved'
     AND nwac_decision_note IS NULL
     AND archived_at IS NULL
     AND updated_at = '2026-08-05 18:27:25'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_workflow_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_review_workflow_event
   WHERE review_workflow_id = 17
   FOR UPDATE;
  IF v_guard_count <> 12 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_workflow_history_count_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_review_workflow_event
   WHERE id = 267
     AND review_workflow_id = 17
     AND action = 'nwac_approve'
     AND from_stage = 'nwac_review'
     AND to_stage = 'final_decision_recorded'
     AND actor_staff_profile_id = 51
     AND actor_role = 'NWAC Administrator'
     AND created_at = '2026-08-05 18:27:25'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_latest_event_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_review_workflow_event
   WHERE review_workflow_id = 17
     AND action = 'system_return_to_submitter_after_failed_correction_recovery'
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_recovery_event_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case_action_plan
   WHERE application_id = 61
   FOR UPDATE;
  IF v_guard_count <> 2 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_application_plan_count_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case_action_plan
   WHERE id = 169
     AND case_id = 138
     AND application_id = 61
     AND status = 'draft'
     AND archived_at IS NULL
     AND created_at = '2026-08-05 18:27:25'
     AND updated_at = '2026-08-05 18:27:25'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_plan_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case_action_plan
   WHERE id = 166
     AND case_id = 138
     AND application_id = 61
     AND status = 'archived'
     AND archived_at = '2026-08-05 16:09:15'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_prior_plan_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case_intervention
   WHERE action_plan_id = 169
   FOR UPDATE;
  IF v_guard_count <> 3 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_intervention_count_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case_intervention
   WHERE id IN (360, 361, 362)
     AND case_id = 138
     AND action_plan_id = 169
     AND status = 'approved'
     AND delivery_status = 'planned'
     AND actual_amount IS NULL
     AND closed_at IS NULL
     AND created_at = '2026-08-05 18:27:25'
     AND updated_at = '2026-08-05 18:27:25'
   FOR UPDATE;
  IF v_guard_count <> 3 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_intervention_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM cfa_version
   WHERE id = 40
     AND series_id = 41
     AND version_number = 2
     AND status = 'draft'
     AND supersedes_version_id = 37
     AND sent_at IS NULL
     AND signed_at IS NULL
     AND created_at = '2026-08-05 18:27:25'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_cfa_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM cfa_version
   WHERE id = 37
     AND series_id = 41
     AND version_number = 1
     AND status = 'withdrawn'
     AND sent_at IS NULL
     AND signed_at IS NULL
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_prior_cfa_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM cfa_version_documents
   WHERE cfa_version_id = 40
   FOR UPDATE;
  IF v_guard_count <> 2 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_cfa_document_count_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM cfa_version_documents
   WHERE (id = 43 AND cfa_version_id = 40 AND document_type = 'clean' AND document_id = 9527)
      OR (id = 44 AND cfa_version_id = 40 AND document_type = 'redline' AND document_id = 9528)
   FOR UPDATE;
  IF v_guard_count <> 2 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_cfa_document_link_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_document
   WHERE id IN (9527, 9528, 9529)
     AND case_id = 138
     AND client_id = 160
     AND application_id = 61
     AND signing_request_id IS NULL
     AND source = 'system_generated'
     AND visibility = 'internal'
     AND status = 'active'
   FOR UPDATE;
  IF v_guard_count <> 3 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_document_count_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_document
   WHERE id IN (9527, 9528)
     AND action_plan_id = 169
     AND document_category = 'funding_agreement'
   FOR UPDATE;
  IF v_guard_count <> 2 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_cfa_document_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_document
   WHERE id = 9529
     AND action_plan_id IS NULL
     AND document_category = 'case_assessment_approved'
     AND created_at = '2026-08-05 18:27:31'
     AND updated_at = '2026-08-05 18:27:31'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_approved_assessment_document_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM signing_request
   WHERE case_id = 138
     AND checklist_doc_type = 'funding_agreement'
     AND created_at >= '2026-08-05 18:27:25'
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_signing_request_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM esdc_participant_submission
   WHERE id = 439
     AND case_id = 138
     AND action_plan_id = 169
     AND application_id = 61
     AND readiness_status = 'needs_review'
     AND submission_status = 'pending'
     AND submitted_at IS NULL
     AND submitted_by_user_id IS NULL
     AND payload_snapshot IS NULL
     AND payload_storage_key IS NULL
     AND payload_checksum IS NULL
     AND rejection_reason IS NULL
     AND created_at = '2026-08-05 18:27:25'
     AND updated_at = '2026-08-05 18:27:25'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_esdc_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_intervention_proposal
   WHERE action_plan_id = 169
      OR legacy_intervention_id IN (360, 361, 362)
      OR source_intervention_id IN (360, 361, 362)
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_proposal_dependency_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_document_intervention
   WHERE intervention_id IN (360, 361, 362)
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_intervention_document_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM payment_packet
   WHERE intervention_id IN (360, 361, 362)
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_payment_packet_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM payment_packet_line
   WHERE intervention_id IN (360, 361, 362)
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_payment_line_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM finance_transaction
   WHERE case_intervention_id IN (360, 361, 362)
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_finance_transaction_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM admin_feedback_report
   WHERE id = 178
     AND status = 'in_progress'
     AND severity = 'high'
     AND summary = 'Make a change on an approved application'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_feedback_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case_note
   WHERE case_id = 138
     AND body LIKE 'SYSTEM_ADMIN_SECOND_RECOVERY_20260806_FEEDBACK_178:%'
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_case_note_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM admin_feedback_note
   WHERE report_id = 178
     AND note_text LIKE 'SYSTEM_ADMIN_SECOND_RECOVERY_20260806_FEEDBACK_178:%'
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_feedback_note_exists';
  END IF;

  UPDATE iset_case_intervention
     SET status = 'cancelled',
         delivery_status = 'cancelled',
         updated_at = CURRENT_TIMESTAMP
   WHERE id IN (360, 361, 362)
     AND case_id = 138
     AND action_plan_id = 169
     AND status = 'approved'
     AND delivery_status = 'planned'
     AND actual_amount IS NULL
     AND closed_at IS NULL;
  IF ROW_COUNT() <> 3 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_intervention_update_failed';
  END IF;

  UPDATE iset_case_action_plan
     SET status = 'archived',
         archived_at = CURRENT_TIMESTAMP,
         updated_at = CURRENT_TIMESTAMP
   WHERE id = 169
     AND case_id = 138
     AND application_id = 61
     AND status = 'draft'
     AND archived_at IS NULL;
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_plan_update_failed';
  END IF;

  DELETE FROM esdc_participant_submission
   WHERE id = 439
     AND case_id = 138
     AND action_plan_id = 169
     AND application_id = 61
     AND readiness_status = 'needs_review'
     AND submission_status = 'pending'
     AND submitted_at IS NULL
     AND submitted_by_user_id IS NULL
     AND payload_snapshot IS NULL
     AND payload_storage_key IS NULL
     AND payload_checksum IS NULL
     AND rejection_reason IS NULL;
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_esdc_delete_failed';
  END IF;

  UPDATE cfa_version
     SET status = 'withdrawn'
   WHERE id = 40
     AND series_id = 41
     AND status = 'draft'
     AND sent_at IS NULL
     AND signed_at IS NULL;
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_cfa_update_failed';
  END IF;

  UPDATE iset_document
     SET status = 'archived',
         updated_at = CURRENT_TIMESTAMP
   WHERE id IN (9527, 9528, 9529)
     AND case_id = 138
     AND client_id = 160
     AND application_id = 61
     AND signing_request_id IS NULL
     AND source = 'system_generated'
     AND status = 'active';
  IF ROW_COUNT() <> 3 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_document_update_failed';
  END IF;

  UPDATE iset_application
     SET status = 'in_review',
         lifecycle_status = 'in_review',
         decision_outcome = NULL,
         awaiting_reason = 'none',
         closure_reason = NULL,
         row_version = row_version + 1,
         updated_at = CURRENT_TIMESTAMP
   WHERE id = 61
     AND case_id = 138
     AND client_id = 160
     AND status = 'approved'
     AND lifecycle_status = 'decision_recorded'
     AND decision_outcome = 'approved'
     AND row_version = 43;
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_application_update_failed';
  END IF;

  UPDATE iset_case
     SET case_context_json = JSON_REMOVE(
           case_context_json,
           '$.assessmentOtherFunding',
           '$.assessment_nwac_review_status',
           '$.decisionLetterDrafts',
           '$.decision_letter_drafts',
           '$.decisionLetter',
           '$.decision_letter',
           '$.decisionLetterPackDrafts',
           '$.decision_letter_pack_drafts',
           '$.decisionLetterSent',
           '$.decision_letter_sent',
           '$.decisionLetterSentType',
           '$.decision_letter_sent_type',
           '$.decisionLetterSentAt',
           '$.decision_letter_sent_at',
           '$.fundingDecisionReasonCode',
           '$.fundingDecisionReasonLabel',
           '$.fundingDecisionReasonExplanation',
           '$.applicationDecisionLetters."61".assessment_nwac_review_status',
           '$.applicationDecisionLetters."61".decisionLetterDrafts',
           '$.applicationDecisionLetters."61".decision_letter_drafts',
           '$.applicationDecisionLetters."61".decisionLetter',
           '$.applicationDecisionLetters."61".decision_letter',
           '$.applicationDecisionLetters."61".decisionLetterPackDrafts',
           '$.applicationDecisionLetters."61".decision_letter_pack_drafts',
           '$.applicationDecisionLetters."61".decisionLetterSent',
           '$.applicationDecisionLetters."61".decision_letter_sent',
           '$.applicationDecisionLetters."61".decisionLetterSentType',
           '$.applicationDecisionLetters."61".decision_letter_sent_type',
           '$.applicationDecisionLetters."61".decisionLetterSentAt',
           '$.applicationDecisionLetters."61".decision_letter_sent_at',
           '$.applicationDecisionLetters."61".fundingDecisionReasonCode',
           '$.applicationDecisionLetters."61".fundingDecisionReasonLabel',
           '$.applicationDecisionLetters."61".fundingDecisionReasonExplanation'
         ),
         updated_at = CURRENT_TIMESTAMP
   WHERE id = 138
     AND client_id = 160
     AND assigned_staff_profile_id = 5697
     AND JSON_UNQUOTE(JSON_EXTRACT(
           case_context_json,
           '$.applicationDecisionLetters."61".assessment_nwac_review_status'
         )) = 'approve';
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_case_context_update_failed';
  END IF;

  UPDATE iset_review_workflow
     SET current_stage = 'returned_to_submitter',
         current_owner_role = 'Submitter',
         current_owner_staff_profile_id = NULL,
         rm_reviewed_by_staff_profile_id = NULL,
         rm_reviewed_at = NULL,
         rm_review_note = 'System Administrator recovery note: The assessment was sent for another final decision before the Coordinator made the required correction. Correct the funding dollar amounts already identified by program staff, save the assessment, and resubmit it for review.',
         nwac_decided_by_staff_profile_id = NULL,
         nwac_decided_at = NULL,
         nwac_decision = NULL,
         nwac_decision_note = NULL,
         metadata_json = '{"source":"system_admin_failed_correction_recovery","feedbackReportId":178,"snapshotId":"path-prod-feedback-178-second-recovery-20260806-2033","requiresSubmitterCorrectionReturn":false}',
         archived_at = NULL,
         updated_at = CURRENT_TIMESTAMP
   WHERE id = 17
     AND workflow_type = 'application_assessment'
     AND subject_key = 'application_assessment:application:61'
     AND case_id = 138
     AND application_id = 61
     AND current_stage = 'final_decision_recorded'
     AND nwac_decision = 'approved';
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_workflow_update_failed';
  END IF;

  INSERT INTO iset_review_workflow_event (
    review_workflow_id,
    workflow_type,
    subject_key,
    action,
    from_stage,
    to_stage,
    actor_staff_profile_id,
    actor_role,
    note,
    payload_json
  ) VALUES (
    17,
    'application_assessment',
    'application_assessment:application:61',
    'system_return_to_submitter_after_failed_correction_recovery',
    'final_decision_recorded',
    'returned_to_submitter',
    NULL,
    'System Administrator',
    'The first correction recovery was bypassed when the unchanged assessment was sent for another final decision. The assessment is now returned directly to the Coordinator for the required funding correction.',
    '{"source":"prod_feedback_178_second_recovery","feedbackReportId":178,"caseId":138,"applicationId":61,"assessmentId":207,"archivedActionPlanId":169,"withdrawnCfaVersionId":40,"snapshotId":"path-prod-feedback-178-second-recovery-20260806-2033"}'
  );
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_workflow_event_insert_failed';
  END IF;

  INSERT INTO iset_case_event (
    case_id,
    event_type,
    summary,
    payload_json,
    occurred_at,
    actor_staff_profile_id,
    actor_user_id,
    source_system
  ) VALUES (
    138,
    'assessment_returned_for_correction_recovery',
    'Assessment returned directly to Coordinator after failed correction handoff',
    '{"runId":"prod-feedback-178-second-recovery-20260806","feedbackReportId":178,"applicationId":61,"reviewWorkflowId":17,"fromStage":"final_decision_recorded","toStage":"returned_to_submitter","archivedActionPlanId":169,"withdrawnCfaVersionId":40,"snapshotId":"path-prod-feedback-178-second-recovery-20260806-2033"}',
    CURRENT_TIMESTAMP(3),
    NULL,
    NULL,
    'system_admin_recovery'
  );
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_case_event_insert_failed';
  END IF;

  INSERT INTO iset_case_note (
    case_id,
    author_staff_profile_id,
    author_user_id,
    body,
    is_internal,
    is_pinned,
    follow_up_at,
    reminder_id
  ) VALUES (
    138,
    NULL,
    NULL,
    'SYSTEM_ADMIN_SECOND_RECOVERY_20260806_FEEDBACK_178: The first correction recovery was bypassed when the unchanged assessment was submitted for another final decision and approved. The assessment is now returned directly to the Coordinator for the required funding-dollar correction. Draft action plan 169, interventions 360-362, CFA version 40, generated documents 9527-9529, and untouched ESDC seed 439 were withdrawn from current use. The earlier approval packet must not be used. After the Coordinator corrects and resubmits, the Regional Manager must review the changed assessment before the Decision Maker records a new decision.',
    1,
    0,
    NULL,
    NULL
  );
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_case_note_insert_failed';
  END IF;

  UPDATE admin_feedback_report
     SET updated_at = CURRENT_TIMESTAMP
   WHERE id = 178
     AND status = 'in_progress'
     AND severity = 'high';
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_feedback_update_failed';
  END IF;

  INSERT INTO admin_feedback_note (
    report_id,
    author_staff_profile_id,
    author_name,
    author_email,
    note_text
  ) VALUES (
    178,
    NULL,
    'System Administrator',
    NULL,
    'SYSTEM_ADMIN_SECOND_RECOVERY_20260806_FEEDBACK_178: Live workflow history proved the first repair reached RM review, but Derry selected Submit for final decision without a Coordinator edit/resubmission and Madison approved the unchanged assessment. A second guarded recovery returned the assessment directly to the submitter, cleared the renewed decision context, archived plan 169, cancelled interventions 360-362, withdrew unsigned/unsent CFA version 40, archived generated documents 9527-9529, and removed untouched ESDC seed 439. No approval letter, signing request, proposal, intervention-document link, payment packet/line, or finance transaction existed. Report remains in progress until the Coordinator correction, resubmission, RM review, renewed decision, and replacement artifacts are independently verified. Snapshot: path-prod-feedback-178-second-recovery-20260806-2033.'
  );
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'feedback_178_second_apply_feedback_note_insert_failed';
  END IF;

  COMMIT;
END//

DELIMITER ;

CALL prod_feedback_178_second_recovery_20260806();
DROP PROCEDURE prod_feedback_178_second_recovery_20260806;
