-- Guarded PROD recovery for Denise Chalifoux application 31 / case 113.
-- Returns the assessment directly to original submitter Derry Yellowfly and
-- withdraws only dependency-free artifacts generated by the accidental denial.
-- Recovery snapshot: path-prod-denise-assessment-recovery-20260819-150930

DROP PROCEDURE IF EXISTS prod_denise_chalifoux_assessment_recovery_20260819;

DELIMITER //

CREATE PROCEDURE prod_denise_chalifoux_assessment_recovery_20260819()
BEGIN
  DECLARE v_guard_count INT DEFAULT 0;

  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    RESIGNAL;
  END;

  START TRANSACTION;

  IF BINARY DATABASE() <> BINARY 'iset_intake' THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_wrong_database';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM application_lock
   WHERE application_lock.application_id = 31
     AND application_lock.owner_user_id = 'prod-denise-assessment-recovery-20260819'
     AND application_lock.expires_at > CURRENT_TIMESTAMP
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_lock_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_application
   WHERE iset_application.id = 31
     AND iset_application.submission_id = 31
     AND iset_application.client_id = 108
     AND iset_application.case_id = 113
     AND iset_application.status = 'in_review'
     AND iset_application.lifecycle_status = 'in_review'
     AND iset_application.decision_outcome IS NULL
     AND iset_application.awaiting_reason = 'none'
     AND iset_application.closure_reason IS NULL
     AND iset_application.row_version = 28
     AND iset_application.updated_at = '2026-08-19 13:54:53'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_application_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case
   WHERE iset_case.id = 113
     AND iset_case.case_number = 'MI-MO7KDW61-115613'
     AND iset_case.client_id = 108
     AND iset_case.assigned_staff_profile_id = 995581
     AND iset_case.status = 'closed'
     AND iset_case.lifecycle_status = 'closed'
     AND iset_case.closure_reason = 'application_denied'
     AND iset_case.stage = 'intake'
     AND iset_case.sub_stage IS NULL
     AND iset_case.closed_at = '2026-08-19 00:00:00'
     AND iset_case.portfolio_region_id = 1
     AND iset_case.open_intervention_count = 0
     AND iset_case.total_intervention_count = 0
     AND iset_case.updated_by_staff_profile_id = 54
     AND iset_case.updated_at = '2026-08-19 13:18:48'
     AND JSON_UNQUOTE(JSON_EXTRACT(
           iset_case.case_context_json,
           '$.applicationDecisionLetters."31".assessment_nwac_review_status'
         )) = 'reject'
     AND JSON_UNQUOTE(JSON_EXTRACT(
           iset_case.case_context_json,
           '$.reportingSeedSource'
         )) = 'denied_reporting'
     AND JSON_UNQUOTE(JSON_EXTRACT(
           iset_case.case_context_json,
           '$.reportingTrigger'
         )) = 'denial'
     AND JSON_UNQUOTE(JSON_EXTRACT(
           iset_case.case_context_json,
           '$.reportingOnlyDenied'
         )) = 'true'
     AND JSON_UNQUOTE(JSON_EXTRACT(
           iset_case.case_context_json,
           '$.reportingCorrectionAllowed'
         )) = 'true'
     AND JSON_UNQUOTE(JSON_EXTRACT(
           iset_case.case_context_json,
           '$.excludeFromCaseworkQueues'
         )) = 'true'
     AND JSON_TYPE(JSON_EXTRACT(
           iset_case.case_context_json,
           '$.applicationReportingArtifacts'
         )) = 'OBJECT'
     AND JSON_LENGTH(JSON_EXTRACT(
           iset_case.case_context_json,
           '$.applicationReportingArtifacts'
         )) = 1
     AND JSON_EXTRACT(
           iset_case.case_context_json,
           '$.applicationReportingArtifacts."31"'
         ) IS NOT NULL
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_case_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_application_assessment
   WHERE iset_application_assessment.id = 34
     AND iset_application_assessment.application_id = 31
     AND iset_application_assessment.case_id = 113
     AND iset_application_assessment.date_of_assessment = '2026-08-18'
     AND iset_application_assessment.esdc_eligibility = 'EI Reach Back'
     AND iset_application_assessment.intervention_code = 1
     AND iset_application_assessment.intervention_outcome_code IS NULL
     AND iset_application_assessment.intervention_cost_total = 18450.00
     AND iset_application_assessment.recommendation = 'recommend'
     AND iset_application_assessment.nwac_review = 'disagree'
     AND iset_application_assessment.nwac_reason = 'Campbell College is a private institution. '
     AND iset_application_assessment.updated_at = '2026-08-19 13:18:48'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_assessment_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_review_workflow
   WHERE iset_review_workflow.id = 59
     AND iset_review_workflow.workflow_type = 'application_assessment'
     AND iset_review_workflow.subject_key = 'application_assessment:application:31'
     AND iset_review_workflow.case_id = 113
     AND iset_review_workflow.application_id = 31
     AND iset_review_workflow.current_stage = 'final_decision_recorded'
     AND iset_review_workflow.current_owner_role IS NULL
     AND iset_review_workflow.current_owner_staff_profile_id IS NULL
     AND iset_review_workflow.submitted_by_staff_profile_id = 995581
     AND iset_review_workflow.submitted_at = '2026-08-18 12:44:33'
     AND iset_review_workflow.rm_reviewed_by_staff_profile_id = 995581
     AND iset_review_workflow.rm_reviewed_at = '2026-08-18 12:45:05'
     AND iset_review_workflow.nwac_decided_by_staff_profile_id = 51
     AND iset_review_workflow.nwac_decided_at = '2026-08-19 13:18:48'
     AND iset_review_workflow.nwac_decision = 'denied'
     AND iset_review_workflow.nwac_decision_note = 'Campbell College is a private institution.'
     AND iset_review_workflow.archived_at IS NULL
     AND iset_review_workflow.updated_at = '2026-08-19 13:18:48'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_workflow_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_review_workflow_event
   WHERE iset_review_workflow_event.review_workflow_id = 59
   FOR UPDATE;
  IF v_guard_count <> 7 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_workflow_history_count_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_review_workflow_event
   WHERE iset_review_workflow_event.id = 403
     AND iset_review_workflow_event.review_workflow_id = 59
     AND iset_review_workflow_event.workflow_type = 'application_assessment'
     AND iset_review_workflow_event.subject_key = 'application_assessment:application:31'
     AND iset_review_workflow_event.action = 'nwac_deny'
     AND iset_review_workflow_event.from_stage = 'nwac_review'
     AND iset_review_workflow_event.to_stage = 'final_decision_recorded'
     AND iset_review_workflow_event.actor_staff_profile_id = 51
     AND iset_review_workflow_event.actor_role = 'NWAC Administrator'
     AND iset_review_workflow_event.created_at = '2026-08-19 13:18:48'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_latest_event_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_review_workflow_event
   WHERE iset_review_workflow_event.review_workflow_id = 59
     AND iset_review_workflow_event.action = 'system_return_to_submitter_after_accidental_denial'
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_recovery_event_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case_action_plan
   WHERE iset_case_action_plan.case_id = 113
      OR iset_case_action_plan.application_id = 31
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_plan_count_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case_action_plan
   WHERE iset_case_action_plan.id = 195
     AND iset_case_action_plan.case_id = 113
     AND iset_case_action_plan.application_id = 31
     AND iset_case_action_plan.name = 'Actions leading to denial'
     AND iset_case_action_plan.status = 'closed'
     AND iset_case_action_plan.owner_staff_profile_id = 995581
     AND iset_case_action_plan.closed_at = '2026-08-19 00:00:00'
     AND iset_case_action_plan.result_code = 1
     AND JSON_UNQUOTE(JSON_EXTRACT(
           iset_case_action_plan.metadata_json,
           '$.source'
         )) = 'denied_reporting'
     AND iset_case_action_plan.archived_at IS NULL
     AND iset_case_action_plan.created_at = '2026-08-19 13:18:48'
     AND iset_case_action_plan.updated_at = '2026-08-19 13:18:48'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_plan_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case_intervention
   WHERE iset_case_intervention.case_id = 113
   FOR UPDATE;
  IF v_guard_count <> 2 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_intervention_count_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case_intervention
   WHERE iset_case_intervention.id IN (424, 425)
     AND iset_case_intervention.case_id = 113
     AND iset_case_intervention.action_plan_id = 195
     AND iset_case_intervention.intervention_code IN (1, 3)
     AND iset_case_intervention.status = 'completed'
     AND iset_case_intervention.delivery_status = 'completed'
     AND iset_case_intervention.start_date = '2026-08-19'
     AND iset_case_intervention.end_date = '2026-08-19'
     AND iset_case_intervention.intervention_cost IS NULL
     AND iset_case_intervention.budget_amount IS NULL
     AND iset_case_intervention.approved_amount IS NULL
     AND iset_case_intervention.actual_amount IS NULL
     AND iset_case_intervention.outcome_code = 1
     AND JSON_UNQUOTE(JSON_EXTRACT(
           iset_case_intervention.metadata_json,
           '$.source'
         )) = 'denied_reporting'
     AND iset_case_intervention.created_by_staff_profile_id = 995581
     AND iset_case_intervention.closed_at = '2026-08-19 00:00:00'
     AND iset_case_intervention.created_at = '2026-08-19 13:18:48'
     AND iset_case_intervention.updated_at = '2026-08-19 13:18:48'
   FOR UPDATE;
  IF v_guard_count <> 2 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_intervention_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM esdc_participant_submission
   WHERE esdc_participant_submission.id = 496
     AND esdc_participant_submission.case_id = 113
     AND esdc_participant_submission.action_plan_id = 195
     AND esdc_participant_submission.application_id = 31
     AND esdc_participant_submission.readiness_status = 'ready'
     AND esdc_participant_submission.submission_status = 'pending'
     AND esdc_participant_submission.submitted_at IS NULL
     AND esdc_participant_submission.submitted_by_user_id IS NULL
     AND esdc_participant_submission.payload_snapshot IS NULL
     AND esdc_participant_submission.payload_storage_key IS NULL
     AND esdc_participant_submission.payload_checksum IS NULL
     AND esdc_participant_submission.rejection_reason IS NULL
     AND esdc_participant_submission.created_at = '2026-08-19 13:18:48'
     AND esdc_participant_submission.updated_at = '2026-08-19 13:18:48'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_esdc_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_document
   WHERE iset_document.id = 11648
     AND iset_document.client_id = 108
     AND iset_document.application_id = 31
     AND iset_document.case_id = 113
     AND iset_document.action_plan_id IS NULL
     AND iset_document.origin_message_id IS NULL
     AND iset_document.signing_request_id IS NULL
     AND iset_document.source = 'system_generated'
     AND iset_document.file_name = 'final-assessment-packet-v2-MI-MO7KDW61-115613.pdf'
     AND iset_document.label = 'Final assessment packet v2 - Denied'
     AND iset_document.status = 'active'
     AND iset_document.document_category = 'case_assessment_approved'
     AND iset_document.created_at = '2026-08-19 13:18:51'
     AND iset_document.updated_at = '2026-08-19 13:18:51'
   FOR UPDATE;
  IF v_guard_count <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_document_guard_failed';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_document_intervention
   WHERE iset_document_intervention.intervention_id IN (424, 425)
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_document_intervention_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_intervention_proposal
   WHERE iset_intervention_proposal.case_id = 113
      OR iset_intervention_proposal.action_plan_id = 195
      OR iset_intervention_proposal.application_id = 31
      OR iset_intervention_proposal.legacy_intervention_id IN (424, 425)
      OR iset_intervention_proposal.source_intervention_id IN (424, 425)
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_proposal_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case_action_item
   WHERE iset_case_action_item.action_plan_id = 195
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_action_item_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case_reminder
   WHERE iset_case_reminder.action_plan_id = 195
      OR iset_case_reminder.intervention_id IN (424, 425)
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_reminder_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM finance_transaction
   WHERE finance_transaction.case_id = 113
      OR finance_transaction.case_intervention_id IN (424, 425)
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_finance_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM payment_packet
   WHERE payment_packet.case_id = 113
      OR payment_packet.client_id = 108
      OR payment_packet.intervention_id IN (424, 425)
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_payment_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM cfa_series
   WHERE cfa_series.case_id = 113
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_cfa_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM messages
   WHERE messages.case_id = 113
     AND messages.created_at >= '2026-08-19 13:18:48'
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_message_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM signing_request
   WHERE signing_request.case_id = 113
     AND signing_request.created_at >= '2026-08-19 13:18:48'
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_signing_request_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case_event
   WHERE iset_case_event.case_id = 113
     AND iset_case_event.occurred_at >= '2026-08-19 13:18:48'
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_case_event_exists';
  END IF;

  SELECT COUNT(*)
    INTO v_guard_count
    FROM iset_case_note
   WHERE iset_case_note.case_id = 113
     AND iset_case_note.body LIKE 'SYSTEM_ADMIN_DENISE_RECOVERY_20260819:%'
   FOR UPDATE;
  IF v_guard_count <> 0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_case_note_exists';
  END IF;

  UPDATE iset_case_intervention
     SET status = 'cancelled',
         delivery_status = 'cancelled',
         updated_at = CURRENT_TIMESTAMP
   WHERE iset_case_intervention.id IN (424, 425)
     AND iset_case_intervention.case_id = 113
     AND iset_case_intervention.action_plan_id = 195
     AND iset_case_intervention.status = 'completed'
     AND iset_case_intervention.delivery_status = 'completed'
     AND iset_case_intervention.actual_amount IS NULL
     AND JSON_UNQUOTE(JSON_EXTRACT(
           iset_case_intervention.metadata_json,
           '$.source'
         )) = 'denied_reporting';
  IF ROW_COUNT() <> 2 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_intervention_update_failed';
  END IF;

  UPDATE iset_case_action_plan
     SET status = 'archived',
         archived_at = CURRENT_TIMESTAMP,
         updated_at = CURRENT_TIMESTAMP
   WHERE iset_case_action_plan.id = 195
     AND iset_case_action_plan.case_id = 113
     AND iset_case_action_plan.application_id = 31
     AND iset_case_action_plan.status = 'closed'
     AND iset_case_action_plan.archived_at IS NULL
     AND JSON_UNQUOTE(JSON_EXTRACT(
           iset_case_action_plan.metadata_json,
           '$.source'
         )) = 'denied_reporting';
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_plan_update_failed';
  END IF;

  DELETE FROM esdc_participant_submission
   WHERE esdc_participant_submission.id = 496
     AND esdc_participant_submission.case_id = 113
     AND esdc_participant_submission.action_plan_id = 195
     AND esdc_participant_submission.application_id = 31
     AND esdc_participant_submission.readiness_status = 'ready'
     AND esdc_participant_submission.submission_status = 'pending'
     AND esdc_participant_submission.submitted_at IS NULL
     AND esdc_participant_submission.submitted_by_user_id IS NULL
     AND esdc_participant_submission.payload_snapshot IS NULL
     AND esdc_participant_submission.payload_storage_key IS NULL
     AND esdc_participant_submission.payload_checksum IS NULL
     AND esdc_participant_submission.rejection_reason IS NULL;
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_esdc_delete_failed';
  END IF;

  UPDATE iset_document
     SET status = 'archived',
         updated_at = CURRENT_TIMESTAMP
   WHERE iset_document.id = 11648
     AND iset_document.client_id = 108
     AND iset_document.application_id = 31
     AND iset_document.case_id = 113
     AND iset_document.origin_message_id IS NULL
     AND iset_document.signing_request_id IS NULL
     AND iset_document.source = 'system_generated'
     AND iset_document.status = 'active';
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_document_update_failed';
  END IF;

  UPDATE iset_application_assessment
     SET nwac_review = NULL,
         nwac_reason = NULL,
         updated_at = CURRENT_TIMESTAMP
   WHERE iset_application_assessment.id = 34
     AND iset_application_assessment.application_id = 31
     AND iset_application_assessment.case_id = 113
     AND iset_application_assessment.nwac_review = 'disagree'
     AND iset_application_assessment.nwac_reason = 'Campbell College is a private institution. ';
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_assessment_update_failed';
  END IF;

  UPDATE iset_application
     SET status = 'in_review',
         lifecycle_status = 'in_review',
         decision_outcome = NULL,
         awaiting_reason = 'none',
         closure_reason = NULL,
         row_version = row_version + 1,
         updated_at = CURRENT_TIMESTAMP
   WHERE iset_application.id = 31
     AND iset_application.case_id = 113
     AND iset_application.client_id = 108
     AND iset_application.status = 'in_review'
     AND iset_application.lifecycle_status = 'in_review'
     AND iset_application.decision_outcome IS NULL
     AND iset_application.row_version = 28;
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_application_update_failed';
  END IF;

  UPDATE iset_case
     SET status = 'intake',
         lifecycle_status = 'intake',
         closure_reason = NULL,
         closed_at = NULL,
         case_context_json = JSON_REMOVE(
           iset_case.case_context_json,
           '$.assessment_nwac_review_status',
           '$.fundingDecisionReasonCode',
           '$.fundingDecisionReasonLabel',
           '$.fundingDecisionReasonExplanation',
           '$.reportingTrigger',
           '$.reportingSeedSource',
           '$.reportingDeniedAt',
           '$.reportingSeededAt',
           '$.reportingLastSyncedAt',
           '$.reportingOnlyDenied',
           '$.reportingOnlyDeniedIneligible',
           '$.reportingCorrectionAllowed',
           '$.excludeFromCaseworkQueues',
           '$.applicationReportingArtifacts',
           '$.applicationDecisionLetters."31".assessment_nwac_review_status'
         ),
         updated_at = CURRENT_TIMESTAMP
   WHERE iset_case.id = 113
     AND iset_case.client_id = 108
     AND iset_case.assigned_staff_profile_id = 995581
     AND iset_case.status = 'closed'
     AND iset_case.lifecycle_status = 'closed'
     AND iset_case.closure_reason = 'application_denied';
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_case_update_failed';
  END IF;

  UPDATE iset_review_workflow
     SET current_stage = 'returned_to_submitter',
         current_owner_role = 'Submitter',
         current_owner_staff_profile_id = NULL,
         rm_reviewed_by_staff_profile_id = NULL,
         rm_reviewed_at = NULL,
         rm_review_note = 'System Administrator recovery: The denial was recorded accidentally. Correct the assessment as intended, save it, and resubmit it for review.',
         nwac_decided_by_staff_profile_id = NULL,
         nwac_decided_at = NULL,
         nwac_decision = NULL,
         nwac_decision_note = NULL,
         metadata_json = '{"source":"system_admin_accidental_denial_recovery","applicationId":31,"caseId":113,"snapshotId":"path-prod-denise-assessment-recovery-20260819-150930","requiresSubmitterCorrectionReturn":false}',
         archived_at = NULL,
         updated_at = CURRENT_TIMESTAMP
   WHERE iset_review_workflow.id = 59
     AND iset_review_workflow.workflow_type = 'application_assessment'
     AND iset_review_workflow.subject_key = 'application_assessment:application:31'
     AND iset_review_workflow.case_id = 113
     AND iset_review_workflow.application_id = 31
     AND iset_review_workflow.current_stage = 'final_decision_recorded'
     AND iset_review_workflow.nwac_decision = 'denied';
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_workflow_update_failed';
  END IF;

  INSERT INTO iset_review_workflow_event (
    review_workflow_id,
    workflow_type,
    subject_key,
    action,
    from_stage,
    to_stage,
    actor_staff_profile_id,
    actor_role,
    note,
    payload_json
  ) VALUES (
    59,
    'application_assessment',
    'application_assessment:application:31',
    'system_return_to_submitter_after_accidental_denial',
    'final_decision_recorded',
    'returned_to_submitter',
    NULL,
    'System Administrator',
    'The denial was recorded accidentally. The assessment was returned directly to original submitter Derry Yellowfly for correction and resubmission.',
    '{"source":"prod_denise_assessment_recovery","caseId":113,"applicationId":31,"assessmentId":34,"archivedActionPlanId":195,"cancelledInterventionIds":[424,425],"removedEsdcSubmissionId":496,"archivedDocumentId":11648,"snapshotId":"path-prod-denise-assessment-recovery-20260819-150930"}'
  );
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_workflow_event_insert_failed';
  END IF;

  INSERT INTO iset_case_event (
    case_id,
    event_type,
    summary,
    payload_json,
    occurred_at,
    actor_staff_profile_id,
    actor_user_id,
    source_system
  ) VALUES (
    113,
    'assessment_returned_for_correction_recovery',
    'Assessment returned to original submitter after accidental denial',
    '{"runId":"prod-denise-assessment-recovery-20260819","applicationId":31,"reviewWorkflowId":59,"fromStage":"final_decision_recorded","toStage":"returned_to_submitter","archivedActionPlanId":195,"cancelledInterventionIds":[424,425],"removedEsdcSubmissionId":496,"archivedDocumentId":11648,"snapshotId":"path-prod-denise-assessment-recovery-20260819-150930"}',
    CURRENT_TIMESTAMP(3),
    NULL,
    NULL,
    'system_admin_recovery'
  );
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_case_event_insert_failed';
  END IF;

  INSERT INTO iset_case_note (
    case_id,
    author_staff_profile_id,
    author_user_id,
    body,
    is_internal,
    is_pinned,
    follow_up_at,
    reminder_id
  ) VALUES (
    113,
    NULL,
    NULL,
    'SYSTEM_ADMIN_DENISE_RECOVERY_20260819: The denial on application 31 was recorded accidentally. The assessment is returned directly to original submitter Derry Yellowfly for correction and resubmission. Denial-generated action plan 195 was archived, interventions 424 and 425 were cancelled, untouched pending ESDC seed 496 was removed, and denied assessment packet 11648 was archived. No messages, signatures, proposals, payments, finance transactions, CFA records, or submitted reporting depended on those artifacts. The original denial remains in the workflow audit history. Snapshot: path-prod-denise-assessment-recovery-20260819-150930.',
    1,
    0,
    NULL,
    NULL
  );
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_case_note_insert_failed';
  END IF;

  DELETE FROM application_lock
   WHERE application_lock.application_id = 31
     AND application_lock.owner_user_id = 'prod-denise-assessment-recovery-20260819';
  IF ROW_COUNT() <> 1 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'denise_recovery_apply_lock_delete_failed';
  END IF;

  COMMIT;
END//

DELIMITER ;

CALL prod_denise_chalifoux_assessment_recovery_20260819();
DROP PROCEDURE prod_denise_chalifoux_assessment_recovery_20260819;
