-- CR-0008 Case Workspace: tasks, action plans, and action items

CREATE TABLE `iset_case_task` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `case_id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `status` VARCHAR(32) NOT NULL DEFAULT 'open',
  `category` VARCHAR(64) DEFAULT NULL,
  `priority` VARCHAR(16) DEFAULT NULL,
  `assigned_to_staff_profile_id` BIGINT UNSIGNED DEFAULT NULL,
  `assigned_to_user_id` INT DEFAULT NULL,
  `due_at` DATETIME DEFAULT NULL,
  `completed_at` DATETIME DEFAULT NULL,
  `created_by_staff_profile_id` BIGINT UNSIGNED DEFAULT NULL,
  `created_by_user_id` INT DEFAULT NULL,
  `updated_by_staff_profile_id` BIGINT UNSIGNED DEFAULT NULL,
  `updated_by_user_id` INT DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_case_task_case_status_due` (`case_id`, `status`, `due_at`),
  KEY `idx_case_task_assignee_status` (`assigned_to_staff_profile_id`, `status`, `due_at`),
  CONSTRAINT `fk_case_task_case` FOREIGN KEY (`case_id`) REFERENCES `iset_case` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_case_task_assignee_profile` FOREIGN KEY (`assigned_to_staff_profile_id`) REFERENCES `staff_profiles` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_case_task_assignee_user` FOREIGN KEY (`assigned_to_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_case_task_created_by` FOREIGN KEY (`created_by_staff_profile_id`) REFERENCES `staff_profiles` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_case_task_updated_by` FOREIGN KEY (`updated_by_staff_profile_id`) REFERENCES `staff_profiles` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `iset_case_action_plan` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `case_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'draft',
  `version` INT NOT NULL DEFAULT 1,
  `owner_staff_profile_id` BIGINT UNSIGNED DEFAULT NULL,
  `owner_user_id` INT DEFAULT NULL,
  `effective_date` DATE DEFAULT NULL,
  `review_date` DATE DEFAULT NULL,
  `notes` TEXT,
  `metadata_json` JSON DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `archived_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_case_action_plan_case_status` (`case_id`, `status`),
  CONSTRAINT `fk_case_action_plan_case` FOREIGN KEY (`case_id`) REFERENCES `iset_case` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_case_action_plan_owner_profile` FOREIGN KEY (`owner_staff_profile_id`) REFERENCES `staff_profiles` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_case_action_plan_owner_user` FOREIGN KEY (`owner_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `iset_case_action_item` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `action_plan_id` BIGINT UNSIGNED NOT NULL,
  `case_id` BIGINT UNSIGNED NOT NULL,
  `sequence` INT DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `status` VARCHAR(32) NOT NULL DEFAULT 'planned',
  `target_date` DATE DEFAULT NULL,
  `completed_at` DATETIME DEFAULT NULL,
  `outcome_note` TEXT,
  `assigned_to_staff_profile_id` BIGINT UNSIGNED DEFAULT NULL,
  `assigned_to_user_id` INT DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_case_action_item_plan_seq` (`action_plan_id`, `sequence`),
  KEY `idx_case_action_item_case_status` (`case_id`, `status`),
  CONSTRAINT `fk_case_action_item_plan` FOREIGN KEY (`action_plan_id`) REFERENCES `iset_case_action_plan` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_case_action_item_case` FOREIGN KEY (`case_id`) REFERENCES `iset_case` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_case_action_item_assignee_profile` FOREIGN KEY (`assigned_to_staff_profile_id`) REFERENCES `staff_profiles` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_case_action_item_assignee_user` FOREIGN KEY (`assigned_to_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
