-- Creates the reminders table used by the Case Calendar and related widgets
-- Supports generic reminders (no case/application) as well as case-linked items

CREATE TABLE IF NOT EXISTS `iset_case_reminder` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `case_id` BIGINT UNSIGNED NULL,
  `application_id` BIGINT UNSIGNED NULL,
  `action_plan_id` BIGINT UNSIGNED NULL,
  `intervention_id` BIGINT UNSIGNED NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `category` VARCHAR(100) NULL,
  `status` ENUM('open','completed','cancelled') NOT NULL DEFAULT 'open',
  `due_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  `completed_by_staff_profile_id` BIGINT UNSIGNED NULL,
  `assigned_staff_profile_id` BIGINT UNSIGNED NULL,
  `metadata_json` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by_staff_profile_id` BIGINT UNSIGNED NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by_staff_profile_id` BIGINT UNSIGNED NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_case_reminder_case_due` (`case_id`, `due_at`),
  KEY `idx_case_reminder_status_due` (`status`, `due_at`),
  KEY `idx_case_reminder_application` (`application_id`),
  KEY `idx_case_reminder_action_plan` (`action_plan_id`),
  KEY `idx_case_reminder_intervention` (`intervention_id`),
  CONSTRAINT `fk_case_reminder_case` FOREIGN KEY (`case_id`) REFERENCES `iset_case`(`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_case_reminder_application` FOREIGN KEY (`application_id`) REFERENCES `iset_application`(`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_case_reminder_action_plan` FOREIGN KEY (`action_plan_id`) REFERENCES `iset_case_action_plan`(`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_case_reminder_intervention` FOREIGN KEY (`intervention_id`) REFERENCES `iset_case_intervention`(`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_case_reminder_completed_by` FOREIGN KEY (`completed_by_staff_profile_id`) REFERENCES `staff_profiles`(`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_case_reminder_assigned_to` FOREIGN KEY (`assigned_staff_profile_id`) REFERENCES `staff_profiles`(`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_case_reminder_created_by` FOREIGN KEY (`created_by_staff_profile_id`) REFERENCES `staff_profiles`(`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_case_reminder_updated_by` FOREIGN KEY (`updated_by_staff_profile_id`) REFERENCES `staff_profiles`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
